### ISSUE TITLE
Don't work with Chrome 53

### ISSUE THREAD

**Issue by lars18th** [lambrospetrou/gmail-keep-importer#1]
Hi,

With the last version of the Chrome Browser it don't works.
Please, can you fix it?

Thank you!

**Comment by lambrospetrou** [comment]
I don't think it's Chrome's problem. The Keep website had a major design overhaul couple months after the last update of the extension which broke the functionality.

I will see if I have some time to update it during the weekend but I do not promise anything. Until Google release an API for Keep this will always be a problem whenever they update their site unfortunately.

**Comment by lars18th** [comment]
Thank you, in any case!

**Comment by lambrospetrou** [comment]
Try to visit the Keep page where the notes are and not in the new homepage. It should still work when run from there.

https://keep.google.com/#home

**Comment by lars18th** [comment]
Hi,

It doesn't work! I confirm today!

I do all the steps described in the help: 
http://github.com/lambrospetrou/gmail-keep-importer#how-to-use

Then I put only one message in my "Notes" folder of the GMail (I renamed my real "Notes" folder to another name because a lot of messages in).

After select the extension:

* LP Gmail-Keep Importer
* Import GMail Label
* Please wait
* Processing your emails...

And after a some time, nothing happens. !?
Where you think is the problem?

**Comment by lars18th** [comment]
FYI,

In the Console only this appears:

```
Service Worker termination by a timeout timer was canceled because DevTools is attached.
```

And, I'm not using the English language... perhaps the problem is related to this. :(
