### ISSUE TITLE
Confirms it imports "Notes" from Gmail but nothing in Google Keep

### ISSUE THREAD

**Issue by eadickey** [lambrospetrou/gmail-keep-importer#17]
Confirms it imports multiple "Notes" from Gmail but nothing in Google Keep.  Am on the home page and have signed out of Keep and back in.  I tried searching for the notes but couldn't find.

**Comment by lambrospetrou** [comment]
Duplicate of https://github.com/lambrospetrou/gmail-keep-importer/issues/16
