### ISSUE TITLE
Any chance of an update?

### ISSUE THREAD

**Issue by timblr1989** [lambrospetrou/gmail-keep-importer#18]
This extension no longer works as it has not been updated to comply with Google's security settings.
Is there ever going to be an update for it, or is there a way to bypass the security?
Recently moved from iPhone to Android and need to move my Notes over!

**Comment by lambrospetrou** [comment]
Sorry, I won't invest any more time chasing the stupid Google policies for extensions. You can download the extension and install it in your local Chrome installation and use it without issues but you will need your own Gmail Key.
