### ISSUE TITLE
"Sign in with Google temporarily disabled for this app" error

### ISSUE THREAD

**Issue by chenango** [lambrospetrou/gmail-keep-importer#19]
When I attempt to import, it asks for my Gmail sign in, then says:

"Sign in with Google temporarily disabled for this app
This app has not been verified yet by Google in order to use Google Sign In."

Is there a workaround available for this?

**Comment by lambrospetrou** [comment]
The extension needs to be go through the Google policy changes again, which I did not do due to time and then changing it too often.

See #16 for more details.

Closing this as duplicate.
