### ISSUE TITLE
LP Gmail Keeper Importer issue

### ISSUE THREAD

**Issue by rmcclarry** [lambrospetrou/gmail-keep-importer#5]
Hi,
I want to move my gmail notes into Keep.  I have followed the instructions to the letter (even through developer mode) and still receive "undefined" during the import process.  LPG2K finds all of the notes, but will not import them.  Help...I tried to take Snippet shots, but cannot show them here fro some reason (see copy/paste results below).
Thanks!

 LP Gmail-Keep Importer

Notes
Import GMail Label
Results

Total messages to import 155

Start importing messages
------------------------------------------------------------------------------------------------
LP Gmail-Keep Importer

Notes
Import GMail Label
Results

undefined

**Comment by lambrospetrou** [comment]
Please try to follow the instructions regarding the website you have to be so that the plugin works. You need to be on the page where the textbox with the DONE button is at the top of the page, otherwise it will not work with the new Keep home page.

**Comment by rmcclarry** [comment]
This all should be on the Keep website outside of Chrome, correct?  I am a novice...

**Comment by lambrospetrou** [comment]
What do you mean outside of Chrome?
The plugin should be used once you are at this website https://keep.google.com/#home 
The new note text box should be at the top where you also have the DONE button. 

If you are, then use the plugin and it should work (at least it worked for others recently).

**Comment by rmcclarry** [comment]
Got it...thanks so much!
