### ISSUE TITLE
Feature Request: Import from Evernote

### ISSUE THREAD

**Issue by leocaseiro** [lambrospetrou/gmail-keep-importer#7]
Hi, thanks for this extension.

I was wondering if we could extend this extension to import from Evernote (Evernote has an export feature).

PS: I've tried to find how to import from Apple Notes, so I would extend to Evernote, but I couldn't find easy instructions or how to do.

**Comment by lambrospetrou** [comment]
Hello,
I am not planning on adding this feature to be honest, since I am not a user of Evernote anyway.
I have no problem accepting a good-written PR though.

**Comment by leocaseiro** [comment]
ok, thanks
